version: "3"

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=tadpgweb
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5433:5432
  pgadmin:
    image: fenglc/pgadmin4
    environment:
      - DEFAULT_USER=admin
      - DEFAULT_PASSWORD=admin
    volumes:
       - ./data/pgadmin:/root/.pgadmin
    ports:
      - 5050:5050
  spoon:
    image: hiromuhota/webspoon:0.8.0.16 
    ports:
      - 8181:8080
    volumes:
      - ./spoon/:/root/.kettle/data/



